exclude: ['README.md', 'CNAME', 'Gemfile', 'vendor']
permalink: pretty
name: 'Зелёный коридор'
description: 'Сайт самодеятельной экологической организации "Зелёный коридор" гимназии №1543'
url: 'https://zelkor1.github.io'
pagination:
 enabled: true
 per_page: 5
 title: ':title — страница :num'
 permalink: '/page:num/'
 sort_reverse: true
 trail:
   before: 2
   after: 2
repository: "zelkor/zelkor.github.io"
